### PR TITLE
Update oss.xml

### PR DESCRIPTION
**Pull request by Miustone**
Updated revision from android-13.0.0_r1 to android-13.0.0_r4

### CODE REVIEW

**Comment by MarijnS95** [comment]
This branch shouldn't even have a revision designator... Why does it?

**Comment by Miustone** [comment]
Good Question. Syncing the Master Branch does not work with Android 13 btw (intended?). Trying this Branch now...

**Comment by jerpelea** [comment]
there is no need to update the xml

**Comment by MarijnS95** [comment]
https://github.com/sonyxperiadev/repo_update/branches/all?query=android-13

That branch doesn't exist anyway.

@jerpelea can you rename it to something more normal?

**Comment by MarijnS95** [comment]
> Syncing the Master Branch does not work with Android 13 btw (intended?).

Look at the reverts, but you're right that `master` is a mess.

- `s-mr1`: Android 12
- `t-mr1`: Android 13 (you want this)
- `master`: most of the things from `t-mr1` reverted again to look like `s-mr1`, but with work-in-progress for Nagara.

**Comment by jerpelea** [comment]
@MarijnS95 NO! we had this case before
If there will be changes on ex r23 we will create that branch and use it from that point (for the same Android version)

**Comment by Miustone** [comment]
@jerpelea why does syncing Master with android-13.0.0_r1 and android-13.0.0_r4 not work in this Case? It always worked before with new Android Releases... I am using r4 rn

**Comment by jerpelea** [comment]
@MarijnS95 master is not a mess it is configured for Android 12 (nagara bring-up) and will be updated to Android 13 once the bring-up is completed

**Comment by Miustone** [comment]
Stop posting Guides in this Case. It does simply not work...
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-13

**Comment by jerpelea** [comment]
@Miustone there is a build guide that can be used for _r4 instead of using master (used for development)

https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-13

**Comment by MarijnS95** [comment]
> @jerpelea why does syncing Master with android-13.0.0_r1 and android-13.0.0_r4 not work in this Case? It always worked before with new Android Releases... I am using r4 rn

You might want to clarify what "doesn't work": create an issue on the bug_tracker _with log output_.



> @MarijnS95 master is not a mess it is configured for Android 12 (nagara bring-up) and will be updated to Android 13 once the bring-up is completed

It's filled with `Revert` commits of stuff that was applied directly before, hard to figure out what's (supposed to be) on there.

**Comment by Miustone** [comment]
> @Miustone there is a build guide that can be used for _r4 instead of using master (used for development)
> 
> https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-13

Clone the local_manifests from GitHub using the following commands:
cd .repo
git clone https://github.com/sonyxperiadev/local_manifests
cd local_manifests
git checkout <branch>
cd ../..

Doesnt mention or specify any specific Branches

**Comment by jerpelea** [comment]
> Stop posting Guides in this Case. It does simply not work... https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-13

..../local_manifests# git branch
* android-13.0.0_r4

**Comment by MartinX3** [comment]
> > @Miustone there is a build guide that can be used for _r4 instead of using master (used for development)
> > [developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-13](https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-13)
> 
> Clone the local_manifests from GitHub using the following commands: cd .repo git clone [sonyxperiadev/local_manifests](https://github.com/sonyxperiadev/local_manifests) cd local_manifests git checkout cd ../..
> 
> Doesnt mention or specify any specific Branches

@Miustone it says
```
cd .repo
git clone https://github.com/sonyxperiadev/local_manifests
cd local_manifests
git checkout <branch>
cd ../..
```

**Comment by jerpelea** [comment]
> > @Miustone there is a build guide that can be used for _r4 instead of using master (used for development)
> > https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-13
> 
> Clone the local_manifests from GitHub using the following commands: cd .repo git clone https://github.com/sonyxperiadev/local_manifests cd local_manifests git checkout cd ../..
> 
> Doesnt mention or specify any specific Branches

check step4
1.
mkdir ~/android
cd ~/android
repo init -u https://android.googlesource.com/platform/manifest -b <branch>

2.
cd .repo
git clone https://github.com/sonyxperiadev/local_manifests
cd local_manifests
git checkout <branch>
cd ../..

you are supposed to replace branch with the branch mentioned here
Build information:

    security revision: 2022-09-05
    build: TP1A.220905.004
    branch: **android-13.0.0_r4**

**Comment by Miustone** [comment]
Thanks, that makes now more sense...

No offensive but i heard from many People that they're unable to Sync with local_manifests based on that Guides. Even i wasnt aware that there are Branches for A13 specially... So i am not the only one missing that Out. The Guides seem to be Copy/Pasted since quite a Time and sudo apt-get install mostly does not work with the called Packages. It would be nice if someone could edit the guides for cases like this... Besides an overall Update to "sudo apt install" with the right Packages like zlib1g-dev for example.

git clone https://github.com/sonyxperiadev/local_manifests -b android-13.0.0_r4
Is what i have used...

**Comment by MarijnS95** [comment]
> No offensive but i heard from many People that they're unable to Sync with local_manifests based on that Guides.

If no-one tells us about it, there's nothing we can do. Again, create a descriptive and concise report otherwise it's impossible to know _what_ is broken.

**Comment by jerpelea** [comment]
@Miustone I tested the guide on Ubuntu 20
Unfortunately it is impossible to test all Linux versions that people may have

**Comment by MartinX3** [comment]
The newest Ubuntu LTS is 22.04

**Comment by Miustone** [comment]
> > No offensive but i heard from many People that they're unable to Sync with local_manifests based on that Guides.
> 
> If no-one tells us about it, there's nothing we can do. Again, create a descriptive and concise report otherwise it's impossible to know _what_ is broken (besides typical Ubuntu being behind on packages).

Of course. I feel a bit lonely reporting stuff... Your latest PRs for A13 have solved the Syncing issues, but all that is missing still on Master (Like said before). Otherwise there are no Bugs with syncing. I was just thinking like everyone else that if we get a Guide, everything works like before... Since the Guides are the same. 

@jerpelea Most People like me are using latest Ubuntu (WSL2) in My Case or KDE Neon natively. Both use apt install. zlib1g-dev is the package we need to build...

**Comment by jerpelea** [comment]
> The newest Ubuntu LTS is 22.04

not everybody can be on the latest version :)

**Comment by jerpelea** [comment]
> > > No offensive but i heard from many People that they're unable to Sync with local_manifests based on that Guides.
> > 
> > 
> > If no-one tells us about it, there's nothing we can do. Again, create a descriptive and concise report otherwise it's impossible to know _what_ is broken (besides typical Ubuntu being behind on packages).
> 
> Of course. I feel a bit lonely reporting stuff... Your latest PRs for A13 have solved the Syncing issues, but all that is missing still on Master (Like said before). Otherwise there are no Bugs with syncing. I was just thinking like everyone else that if we get a Guide, everything works like before... Since the Guides are the same.
> 
> @jerpelea Most People like me are using latest Ubuntu (WSL2) in My Case or KDE Neon natively. Both use apt install. zlib1g-dev is the package we need to build...

You are using an unsupported OS to build 

The master branch is intened for development and is expected to have things that are incomplete or not fully tested yet
Please stick to the stable branches mentioned in the build guide

**Comment by Miustone** [comment]
> > The newest Ubuntu LTS is 22.04
> 
> not everybody can be on the latest version :)

You're right, but please consider many People are... (Also at least on WSL2 by default) A hint for that could help frustrated People getting around it. 

@MarijnS95 Right. The Guide tells Me NOTHING about it at all.

**Comment by jerpelea** [comment]
> > > The newest Ubuntu LTS is 22.04
> > 
> > 
> > not everybody can be on the latest version :)
> 
> You're right, but please consider many People are... (Also at least on WSL2 by default) A hint for that could help frustrated People getting around it.
> 
> @MarijnS95 Right. The Guide tells Me NOTHING about it at all.
> 
> Where do i find this Infos under this Link? https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-13#tutorial-step-4

The next step is to create a folder on your computer, and then download the Android source code to it.  To do this, take note of the branch in the Build information and follow the steps below.
Build information:

    security revision: 2022-09-05
    build: TP1A.220905.004
    branch: android-13.0.0_r4

**Comment by MarijnS95** [comment]
> @MarijnS95 Right. The Guide tells Me NOTHING about it at all.
> 
> Where do i find this Infos under this Link? https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-13#tutorial-step-4

image

It's probably just me being stupid though.

**Comment by Miustone** [comment]
Clone to 'local_manifests' …
remote: Enumerating objects: 1994, done.
remote: Counting objects: 100% (252/252), done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 1994 (delta 155), reused 203 (delta 126), pack-reused 1742
Empfange Objekte: 100% (1994/1994), 263.64 KiB | 1.37 MiB/s, fertig.
Löse Unterschiede auf: 100% (1414/1414), fertig.
Ihr Branch ist auf demselben Stand wie 'origin/android-13.0.0_r4'.

And all looks fine. If i dont specify the branch with -b it does not work and says something else (cant remember the Message)

**Comment by MarijnS95** [comment]
> Point is that command (git checkout) does simply not work like that (for me and some others at least) so everyone skipps it staying on Master still.

That's _exactly_ how it works. Again, without sharing the output with us we cannot help you debug this further.

`-b` is a nice alternative though, but _won't work_ when you've already cloned the repo before and are just updating.

**Comment by Miustone** [comment]
> Maybe you're mixing `git` with `repo` `repo init -b ...` works after checkout.

    repo init -u https://android.googlesource.com/platform/manifest -b $BRANCH

    cd .repo

    if [ ! -d ~/dios/.repo/local_manifests ]; then
        git clone https://github.com/sonyxperiadev/local_manifests -b $BRANCH
    fi

    cd local_manifests

    git checkout

    cd ../..
    
    while $BRANCH is [android-13.0.0_r4](https://github.com/sonyxperiadev/local_manifests/tree/android-13.0.0_r4) ofc

Code Fully Syncs like that. Builds also work (i guess) I checked my local_manifests and it's the one i wanted with -b 
Note i wasnt able to use git checkout with a branch. It just worked without

**Comment by MarijnS95** [comment]
`git checkout` is a no-op when not given an argument.

**Comment by Miustone** [comment]
> `git checkout` is a no-op when not given an argument.

But it gave out "same as origin/blabla"

**Comment by Miustone** [comment]
> From `man git-checkout`:
> 
> > You could omit `<branch>`, in which case the command degenerates to "check out the current branch", which is a glorified no-op with rather expensive side-effects to show only the tracking information, if exists, for the current branch.

Got the same ouput with $BRANCH added
German: Ihr Branch ist auf demselben Stand wie 'origin/android-13.0.0_r4'.

**Comment by Miustone** [comment]
> > Got the same ouput with $BRANCH added German: Ihr Branch ist auf demselben Stand wie 'origin/android-13.0.0_r4'.
> 
> Correct, if you're already on it.
> 
> Now imagine the next tag, `android-13.0.0_r1337` is being released and pushed by us. `git checkout` will do nothing. `git checkout $BRANCH` (`BRANCH=android-13.0.0_r1337`) will check out to the newly pushed branch.

Now i got it! Totally makes sense... So while it worked out for Me on a clean PC, it does not work later after Updates and New Branches.  I will remove the Code again and start a sync with:
    repo init -u https://android.googlesource.com/platform/manifest -b $BRANCH

    cd .repo

    if [ ! -d ~/dios/.repo/local_manifests ]; then
        git clone https://github.com/sonyxperiadev/local_manifests
    fi

    cd local_manifests

    git checkout $BRANCH

    cd ../..
    
    Aye!?

**Comment by Miustone** [comment]
German: Branch 'android-13.0.0_r4' folgt nun Remote-Branch 'android-13.0.0_r4' von 'origin'.
Zu neuem Branch 'android-13.0.0_r4' gewechselt

Said it switched Branches. Black Magic... Dunno why it hasnt worked out before. Sorry for beeing annoying and thanks for the Context Guys!

**Pull request closed without merging**
