### PR TITLE
Un-untrack required repos to build 12L

### PR DESCRIPTION
**Pull request by konradybcio**

### CODE REVIEW

**Comment by MartinX3** [comment]
Don't you get the SeLinux compilation error I get?
https://github.com/sonyxperiadev/bug_tracker/issues/762

**Comment by konradybcio** [comment]
Not on xqbc52-eng target at least.

**Comment by konradybcio** [comment]
Not on xqbc52-eng target at least.

**Comment by MartinX3** [comment]
> Not on xqbc52-eng target at least.

thanks, I try it again, maybe I slurped something into hell while adding these missing car repos myself.

**Pull request merged**
