### PR TITLE
untracked: Remove irrelevant device/* and prebuilts paths

### PR DESCRIPTION
**Pull request by AdrianDC**
Change-Id: Ie62d17a46633f456b20bb26c6773a2dbc9910c43
Signed-off-by: Adrian DC <radian.dc@gmail.com>

### CODE REVIEW

**Comment by jerpelea** [comment]
we want to keep those devices for now as an config example

**Comment by AdrianDC** [comment]
Please comment on each you'd like to keep because clearly be do not need to sync kernel prebuilts and so on.

**Comment by jerpelea** [comment]
all real devices should remain

**Comment by AdrianDC** [comment]
Done.

**Comment by jerpelea** [comment]
please leave the generic gits

**Comment by AdrianDC** [comment]
Done².

**Pull request merged**
