### PR TITLE
[master] Move to the new aosp/LA.UM.6.4.r1 kernel

### PR DESCRIPTION
**Pull request by bartcubbins**
This PR can be merged when the 6.4 kernel will be ready.
Also update domain for Sony Developer World site.

### CODE REVIEW

**Comment by jerpelea** [comment]
wrong kernel description 6.4_r1 is the new one

**Comment by bartcubbins** [comment]
@jerpelea typo. updated and force pushed:)

**Comment by oshmoun** [comment]
please also update pr title :)

**Comment by jerpelea** [comment]
please update all read.me

**Comment by bartcubbins** [comment]
@jerpelea all platforms/devices and all branches?

**Comment by jerpelea** [comment]
from n-mr1 on all

**Comment by bartcubbins** [comment]
@jerpelea will do this asap

**Pull request merged**
