### PR TITLE
manifest: fix 3.18 sepolicy

### PR DESCRIPTION
**Pull request by alviteri**
commit 51ae8cab2f58889316735baeee2d3da6ba98fa27 was wrong and it causes do not boot tone devices (dora here) fix it

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by jerpelea** [comment]
fix sepolicy!

**Comment by alviteri** [comment]
so use n-mr1 for both ? @jerpelea

**Comment by alviteri** [comment]
if yes will fix tonight after work

**Comment by jerpelea** [comment]
thanks

**Pull request closed without merging**
