### PR TITLE
Add msm-5.4 / 9.14 sources

### PR DESCRIPTION
**Pull request by konradybcio**

### CODE REVIEW

**Comment by Haxk20** [comment]
@konradybcio rebase when you get time :)

**Comment by MarijnS95** [comment]
Wasn't most if not all of this already cherry-picked/applied by Alin one way or another?

**Comment by Haxk20** [comment]
May have been. But he would close this and say here that he did probably.

**Comment by konradybcio** [comment]
closing as this looks superseded

**Pull request closed without merging**
